# Generated by Django 5.2.5 on 2025-09-04 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='label',
        ),
        migrations.RemoveField(
            model_name='products',
            name='label_en',
        ),
        migrations.RemoveField(
            model_name='products',
            name='label_ky',
        ),
        migrations.RemoveField(
            model_name='products',
            name='label_ru',
        ),
        migrations.AddField(
            model_name='main',
            name='image',
            field=models.ImageField(default=1, upload_to='main_images/'),
            preserve_default=False,
        ),
    ]
