# Generated by Django 5.2.5 on 2025-09-05 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_remove_products_label_remove_products_label_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='title_region',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
